name: lint-and-test
on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.3.2
        with:
          version: v1.64.2
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
